version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: main3.15
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Vladivostok
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: "Зависимости"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
