version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pyinstaller-stack:
        patterns:
          - "pyinstaller"
          - "pyinstaller-hooks-contrib"
      routine-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "Обновить зависимость "
