"""Runtime constants for the doctor orders widget."""

import os


ORDERS_CELL_REPEAT_GUARD_SEC = max(
    0.15,
    float(os.getenv("REMCARD_ORDERS_CELL_REPEAT_GUARD_SEC", "0.45")),
)
ORDERS_POST_FINALIZE_WATCHDOG_MS = max(
    1000,
    int(os.getenv("REMCARD_ORDERS_POST_FINALIZE_WATCHDOG_MS", "7000")),
)
ORDERS_POST_FINALIZE_MAX_RETRIES = max(
    1,
    int(os.getenv("REMCARD_ORDERS_POST_FINALIZE_MAX_RETRIES", "3")),
)
ORDERS_POST_FINALIZE_RETRY_BACKOFF_MS = max(
    1000,
    int(os.getenv("REMCARD_ORDERS_POST_FINALIZE_RETRY_BACKOFF_MS", "5000")),
)
ORDERS_POST_FINALIZE_RETRY_MAX_BACKOFF_MS = max(
    ORDERS_POST_FINALIZE_RETRY_BACKOFF_MS,
    int(os.getenv("REMCARD_ORDERS_POST_FINALIZE_RETRY_MAX_BACKOFF_MS", "30000")),
)
ORDERS_FORCED_RELOAD_COOLDOWN_MS = max(
    250,
    int(os.getenv("REMCARD_ORDERS_FORCED_RELOAD_COOLDOWN_MS", "1500")),
)
